### ISSUE TITLE
Shell is stuck loading when using Firefox Incognito mode

### ISSUE THREAD

**Issue by ttomasz** [duckdb/duckdb-wasm#1014]
When opening https://shell.duckdb.org/ in Firefox Incognito mode the shell gets stuck like in this screenshot:
![image](https://user-images.githubusercontent.com/31594210/192120858-d52ec191-9d82-470b-bdca-e95cade7c2df.png)
In regular Firefox window it works fine:
![image](https://user-images.githubusercontent.com/31594210/192120889-22e6ad54-dc90-4c58-a2eb-26490a38e290.png)

Linux, Firefox 105.0.1

**Comment by carlopi** [comment]
Seems it's actually fixed, thanks again for opening this.

Behaviour now on Firefox incognito, and to some degree situations where indexedDB will fail to initialise, is that a console.warn("") message will inform no history could be loaded/persisted, but the shell will work regularly.

Thanks @ankoh and @domoritz.
