### ISSUE TITLE
Export files via /out/

### ISSUE THREAD

**Issue by ankoh** [duckdb/duckdb-wasm#105]
We should support a pseudo output directory `/out/` in the wasm filesystem.
```
# Exports the relation lineitem to a pseudo file somefile.csv.
COPY lineitem TO '/out/somefile.csv' ( DELIMITER '|', HEADER );

# Exports the database to a pseudo directory somedb.
EXPORT DATABASE '/out/somedb' (FORMAT PARQUET);
```
The shell should check these paths and provide the files to the user via a download dialog.

**Comment by ankoh** [comment]
The shell has the command `.files download $FILE` now. I'd prefer to stick to that since auto downloading requires us to glob after every query.

Outside of the shell, you can always use `db.copyFileToBuffer('/out/somefile.csv')` to get the array buffer.

**Comment by chriszrc** [comment]
@ankoh excuse my ignorance, but can we download the results of the query in wasm shell somehow as well? `.files download $TABLE_NAME` doesn't seem to work-

**Comment by chriszrc** [comment]
@ankoh ok, now I see that I can:

```
COPY mytable TO 'mytable.csv' (FORMAT CSV, HEADER);
.files download mytable.csv
```

Is that the right way? Would it be much different using the API?
