### ISSUE TITLE
[ObservableDuckDBClient] Parameters with table functions

### ISSUE THREAD

**Issue by kimmolinna** [duckdb/duckdb-wasm#1051]
According to @Mytherin parameters work for table functions on the latest version. When I use DuckdDBClient ObservableHQ SQL Cell with external variable which uses a prepared statemetns I will get the following errror message: `Error: Binder Error: Table function requires a constant parameter LINE 3: FROM read_parquet(?)`

@ankoh is this a wasm-version issue or @domoritz 's DuckDBClient one?

**Comment by Mytherin** [comment]
This was fixed in duckdb/duckdb#4059, which was included in DuckDB v0.5 for the first time. We recently upgraded duckdb-wasm to v0.5.1 (#1026). It's likely that Observable is still using duckdb-wasm v0.4. You could check the DuckDB version by running `PRAGMA version`.

**Comment by kimmolinna** [comment]
Library_version `v0.3.4` and source_id `662041e2b`

**Comment by kimmolinna** [comment]
I created a fork with the latest version and It works nicely. Thank you very much @Mytherin

**Comment by domoritz** [comment]
I updated the client.
