### ISSUE TITLE
"Maximum call stack size exceeded" errors in Safari

### ISSUE THREAD

**Issue by ilyabo** [duckdb/duckdb-wasm#1058]
Running the same query for 321 times leads to the error "Maximum call stack size exceeded" in Safari (haven't seen it in Chrome so far)

Minimal app to reproduce the issue: https://github.com/ilyabo/duckdb-safari-maxcallstack-issue/blob/main/pages/index.tsx

Deployed here:
https://duckdb-safari-maxcallstack-issue.pages.dev/

![image](https://user-images.githubusercontent.com/351828/200167021-497f396f-4c2c-49a4-b8b3-0ef6ac5e2bfe.png)

I wasn't able to identify a single particular part of the query causing the issue. But it was apparent that removing different query parts had an impact on how many times the query needed to be executed before the error occurred.

Once this happens, all subsequent queries also fail, only simpler queries don't.

**Comment by ilyabo** [comment]
I could also reproduce the error for a simpler query after running it for 1396 times:

```
SELECT
    f.origin,
    f.dest,
    SUM(f.count) as flow_count
FROM
    flows f
WHERE 
    f.origin <> f.dest
    AND f.count > 0
   AND (epoch_ms(1634018400000) <= time AND time < epoch_ms(1634281200000))

GROUP BY
    f.origin,
    f.dest
    
LIMIT 10
        
```

**Comment by kimmolinna** [comment]
Is this related  to #983?

**Comment by ankoh** [comment]
Thanks for the repro, it crashes for me as well in Safari. I think DuckDB-Wasm has to get better in logging to narrow such issues down a bit easier.

**Comment by ilyabo** [comment]
> Thanks for the repro, it crashes for me as well in Safari. I think DuckDB-Wasm has to get better in logging to narrow such issues down a bit easier.

@ankoh Yes, the error message is not super informative...

The issue might seem rare, but it's a nasty one for my case. I send a lot of queries when the user interacts with the map. As a result, the app stably crashes after like 20 seconds of zooming and panning in the map in Safari :( 
 
It looks like the time until it happens depends on the complexity of the query: the more complex the query, the sooner it crashes. Could it have to do with the query AST traversal?

**Comment by ilyabo** [comment]
I added retries to the app. Very very interestingly, the DB seems to recover after many retries to execute the same query!!! After that it  seems to work fine. 

![image](https://user-images.githubusercontent.com/351828/204889079-1c828265-45c7-4955-9d71-9d712c0ad336.png)

**Comment by ilyabo** [comment]
For the simpler query it sometimes takes two runs of retries to recover:

![image](https://user-images.githubusercontent.com/351828/204890105-4cc67986-c54d-4e5e-ba2c-1555e569c1f0.png)

**Comment by ilyabo** [comment]
This WebKit issue might be related: https://bugs.webkit.org/show_bug.cgi?id=206436

**Comment by ilyabo** [comment]
Looks like forcing duckdb-wasm to use the `-mvp` bundle in Safari prevents the issue from happening so this might be a workaround.

**Comment by carlopi** [comment]
I am unsure at this point if this was a Safari bug to start with, or just a hidden dependency on how postMessage was implemented in other browsers.

The fact that changing between very different Safari version keeps the bug against 1.17, vs solves the bug against 1.24 I think points towards the problem being somewhere in DuckDB-Wasm, but it's hard to say.
