### ISSUE TITLE
Missing s3_url_style env variable for s3 like storage (minio)

### ISSUE THREAD

**Issue by Kokopak** [duckdb/duckdb-wasm#1072]
Hi !

I would like to use this library with my self hosted minio but when I set the `s3_url_style`  ([according to the httpfs documentation](https://duckdb.org/docs/extensions/httpfs.html)) variable like this : 

`await conn.query("SET s3_url_style='path';")`

in order to prevent the use of s3 vhost, it doesn't work and the library keep using s3 vhost (https://bucket_name.endpoint/resource instead of https://endpoint/bucket_name/resource). 

It works in the duckdb-cli and the python library, so I assume it's a problem with the wasm library

**Comment by lmangani** [comment]
As a workaround you can set an explicit s3_endpoint URL including the protocol: 
```
SET s3_endpoint='https://custom.endpoint';
```
