### ISSUE TITLE
SQL Copy statement throws "Invalid Error: unique_lock::unlock : not locked: Operation not permitted"

### ISSUE THREAD

**Issue by rpbouman** [duckdb/duckdb-wasm#1093]
I'm writing a browser-based app that uses duckdb-wasm.

I can register local files using

`duckDbInstance.registerFileHandle(name, file)`

where `name` is a user-entered string, and `file` is a File object from a FileList (https://developer.mozilla.org/en-US/docs/Web/API/File).
This works, and after registering a file, say `C:\Users\Roland_Bouman\Downloads\cities.csv` as `cities.csv`, I can do

`const result = duckDbConnection.query("SELECT * FROM 'cities.csv'");`

and it gives me a table object that I can read and extract data from.

Now I want to export data. So I registered a new, empty file as `empty.csv`.
But when I use the same kind of call to `duckDbConnection.query` to run:

`copy (select * from "cities.csv") to 'empty.csv'(DELIMITER '|', HEADER)`

it throws an exception. Stacktrace:

```
Error: Invalid Error: unique_lock::unlock: not locked: Operation not permitted
    at $o.runQuery (http://localhost:3000/static/media/duckdb-browser-eh.worker.f1606be4b4cf4695eb06.js:11867:26)
    at ac.onMessage (http://localhost:3000/static/media/duckdb-browser-eh.worker.f1606be4b4cf4695eb06.js:10084:38)
    at Zu.globalThis.onmessage (http://localhost:3000/static/media/duckdb-browser-eh.worker.f1606be4b4cf4695eb06.js:12559:15)

```

Why is this happening? Am I doing something wrong? Is there another method I should use to export data to a local file using duckdb-wasm?

Thanks in advance!

**Comment by rpbouman** [comment]
I just realized this is probably no fault of duck db api as Web File API file objects are not writeable. 

I think I figured out how to do what I need to do and will post back when I can explain how.

**Comment by chriszrc** [comment]
@rpbouman so can we create a file for export/download?
