### ISSUE TITLE
Postgres_scanner available in WASM?

### ISSUE THREAD

**Issue by ScottSyms** [duckdb/duckdb-wasm#1095]
Apologies if this has been implemented already- looking at the viability of using DuckDB-WASM as an in-browser caching layer.  Is the postgres_scanner extension on the roadmap for porting?

**Comment by Mause** [comment]
It's unlikely that it will be available as is, as you can't access a raw socket api from within a browser. There's a chance that it may be possible when running inside NodeJS (or perhaps something like wasmer?), but at that point you'd be better off using the native NodeJS bindings

**Comment by ScottSyms** [comment]
tks!
