### ISSUE TITLE
Function `array_length` does not work

### ISSUE THREAD

**Issue by krish-adi** [duckdb/duckdb-wasm#1130]
I am using duckdb-wasm in a project. I load multiple parquet files and run some queries on them. 

One of the queries that throws an error contains the function `array_length()`. This function works on the shell.duckdb.org but does not work on the duckdb-wasm that I downloaded off npm. Are both of them different versions of duckdb-wasm?

I do see that the pkg version of duckdb-wasm on shell.duckdb.org is: @duckdb/duckdb-wasm@1.20.1-dev42.0 , whereas the on on npm is 1.20.0

**Comment by Mause** [comment]
Can you post the error?

**Comment by krish-adi** [comment]
Hey @Mause I figured it out eventually. The problem was at my end of not parsing the data properly.
