### ISSUE TITLE
SELECT INTERVAL 1 DAY hangs the online shell

### ISSUE THREAD

**Issue by orlp** [duckdb/duckdb-wasm#1133]
To reproduce execute the following on https://shell.duckdb.org/:

```sql
SELECT INTERVAL 1 DAY;
```

The error in the Javascript console is

```
125.6dc9a38060e9fe5bb98b.js:1 panicked at 'already mutably borrowed: BorrowError', packages/duckdb-wasm-shell/crate/src/shell.rs:1064:29
```

Unfortunately the Rust stacktrace is empty.

**Comment by carlopi** [comment]
Update: now it's not trapping in the front end anymore!
(but conversions from internal interval representation to Arrow representation needs to be worked on, since here it currently returns:
`0 years 0 mons 0 days 0 hours 0 mins 4.294967296 secs`

**Comment by carlopi** [comment]
And this seems to be the same problem as #1203.

**Comment by carlopi** [comment]
Thanks a lot, this is now solved thanks to https://github.com/duckdb/duckdb-wasm/pull/1769
