### ISSUE TITLE
Test failure during build - missing file "./lib/../data/uni/studenten.parquet"

### ISSUE THREAD

**Issue by davewthompson** [duckdb/duckdb-wasm#1141]
Attempting to build this project:
Mac Pro M1, macOS Monterey, cmake from Homebrew, etc.

```
(...clone repo...)
git submodule init
git submodule update --recursive
make
(...build...)
[----------] 2 tests from ParquetLoadTest
[ RUN      ] ParquetLoadTest.LoadParquet
CHECK_COLUMN: query failed with error IO Error: No files found that match the pattern "./lib/../data/uni/studenten.parquet"
CHECK_COLUMN: Difference in result row count
/Users/dave/Projects/git/public/duckdb/duckdb-wasm/lib/test/parquet_test.cc:29: Failure
Value of: CHECK_COLUMN(*result, 0, {24002, 25403, 26120, 26830, 27550, 28106, 29120, 29555})
  Actual: false
Expected: true
[  FAILED  ] ParquetLoadTest.LoadParquet (42 ms)
```

**Comment by carlopi** [comment]
Thanks for the report, I think a `make data` is missing from the instructions.

Something like:
```
git submodule init
git submodule update --recursive
make data
make
```
Should be closer to the actual solution, please do comment back if you find other hiccups (either here or joining https://discord.duckdb.org).

----

I am working on refactoring the Makefile that should solve this issue, current work is on the branch `makefile_rework` of my fork: https://github.com/carlopi/duckdb-wasm/tree/makefile_rework, potentially even taking that Makefile should ideally work by doing just `make`.

**Comment by davewthompson** [comment]
That works - thank you very much! Is there any contribution document anywhere I can use as a reference?

**Comment by carlopi** [comment]
README / Contribute documents are being worked on, not there yet.

On the integration side, I think https://github.com/duckdb/duckdb-wasm/tree/master/examples and https://github.com/duckdb-wasm-examples are good starting points.

**Comment by carlopi** [comment]
Already solved, while issues on documentation that are partially still open are directed to duckdb-web.
Thanks for trying!
