### ISSUE TITLE
Do Duckdb WASM Supports Angular?

### ISSUE THREAD

**Issue by akash-goel** [duckdb/duckdb-wasm#1187]
Hi Team,

I am working on Angular Project and want to use WASM , I am getting issue in running the Duckdb wasm on Angular, Request you to guide do duckdb supports Angular and Is there any sample project in Angular for Duckdb.

Regards,
AKash

**Comment by carlopi** [comment]
Hi @akash-goel, have you managed to find a way to make duckdb-wasm works with your project?

**Comment by rwreplog** [comment]
I put together a simple app to demonstrate a DuckDB WASM and shell implementation in Angular v16.

It can be referenced [here](https://github.com/rwreplog/angular-duckdb-startup). Hopefully this is helpful to others!

@carlopi Is this something that could be added to the [DuckDB WASM Examples](https://github.com/duckdb-wasm-examples)?

**Comment by domoritz** [comment]
Closing since there is nothing specific that duckdb needs to do to support angular.
