### ISSUE TITLE
Restrictive logic for checking whether a remote parquet file supports range queries

### ISSUE THREAD

**Issue by carstonhernke** [duckdb/duckdb-wasm#1189]
## Issue
When I attempt to query a parquet file I have hosted myself with the DuckDB WASM web shell (https://shell.duckdb.org/), it seems to always fallback to a full HTTP read.

## Cause
I have done a bit of testing and this appears to be because when DuckDB sends its initial `HEAD` request with the Range header, it is expecting an HTTP Response Code of `206`:
https://github.com/duckdb/duckdb-wasm/blob/cceb0ed3db100cebdd5eeecc3178baf3ba912313/packages/duckdb-wasm/src/bindings/runtime_browser.ts#L168

### What works
With the sample file that is provided in the docs (https://shell.duckdb.org/data/tpch/0_01/parquet/customer.parquet), a `HEAD` request with a Range header does return a status code of `206`. However, this response does not seem to be a universal standard.

### What doesn't work
I have tested with two hosted files, one on Github Pages ([here](https://raw.githubusercontent.com/carstonhernke/demo-h3-data/main/parquet/germany_population.parquet)), and one served with AWS Cloudfront ([here](https://honeycomb.carston.org/data/usa_population.parquet)). They both seem to return a status code of `200` for a `HEAD` request with a Range header. **This causes the check above to be false and triggers the fallback to a full HTTP read**. However, both these hosting providers do support HTTP Range requests.

## Potential solutions
I can think of a few solutions here:
- Enhance the logic to test whether a given file can be accessed with Range requests (not an HTTP status code expert, but if the `Accept-Ranges` header is present on the response with a value of `bytes`, this should be enough, right?)
- Add some better documentation explaining the `HEAD` request process and necessary headers, so that users can configure their server/ hosting provider settings accordingly.

**Comment by carlopi** [comment]
Thanks for opening the issue, I did register that full HTTP range requests were used in more cases than needed, but had no chance yet to dig into the relevant code. If you want to send a PR in line with solution 1 (Accept-Ranges present and equal to bytes plus keeping the check on content length being present), it's very welcome!

For reference, I checked the [HTTPFS implementation in mainline duckdb](https://github.com/duckdb/duckdb/blob/master/extension/httpfs/httpfs.cpp#L562), and there the logic looks like to be:
* HEAD == 200 -> check "Content-Range" or "Content-Length"
* HEAD != 200 -> another request with GET with single byte Range -> expect 206 here.
I am not sure whether also there there are cases we might be missing.

**Comment by carlopi** [comment]
Brief update, I have a proper solution here, it requires an additional HEAD request for byte range 0-0, and if that works, we could avoid the full download.

I will later file this, while a restructuring of the code could allow to avoid this extra request.

Thanks again for sharing your finding on this.

**Comment by carstonhernke** [comment]
This looks great, thank you @carlopi for your work on it! Excited to work with this project further.

**Comment by carlopi** [comment]
Earlier today it has been merged in master, and now in the live https://shell.duckdb.org it gives:

![Screenshot 2023-03-21 at 11 15 33](https://user-images.githubusercontent.com/842657/226576613-c8834763-04fd-4822-8bc4-4b5e041448dd.png)
```
duckdb> select count(*) from 'https://shell.duckdb.org/data/tpch/0_01/parquet/customer.parquet';
┌──────────────┐
│ count_star() │
╞══════════════╡
│         1500 │
└──────────────┘
Elapsed: 01.801 s

duckdb> select count(*) from 'https://raw.githubusercontent.com/carstonhernke/demo-h3-data/main/parquet/germany_population.parquet';
┌──────────────┐
│ count_star() │
╞══════════════╡
│       373545 │
└──────────────┘
Elapsed: 02.387 s

duckdb> select count(*) from 'https://honeycomb.carston.org/data/usa_population.parquet';
Invalid Error: NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://honeycomb.carston.org/data/usa_population.parquet'.
```
Could you double check that it also works for your own deployment?

Thanks!

**Comment by carstonhernke** [comment]
Great news! Wow, impressive turnaround.

Looks like both files work for me (I did have to change the CORS settings for the self-hosted file a few days ago, perhaps those were still cached and caused your error):
![image](https://user-images.githubusercontent.com/25538985/226589485-11e8ee5d-147a-4e4a-90c2-a8f0b4caa07e.png)
