### ISSUE TITLE
Support for the sqlite_scanner extension in duckdb-wasm?

### ISSUE THREAD

**Issue by mattijn** [duckdb/duckdb-wasm#1190]
First of all, I'm much grateful for the existence of this package. Thanks for building it!

I'm not completely sure if my issue is a feature request or a question. 

I was trying to use duckdb-wasm in combination with the duckdb SQLite scanner. This would enable use to analyze some rather large SQLite files that are generated in another process in the browser on the client-side. I noticed that DuckDB has a useful sqlite_scanner extension for scanning SQLite databases.

While there is no support for this extension in https://shell.duckdb.org, I was wondering if there are build options that can make it possible already? Or are there are any limitations that prevent it from being included?

**Comment by carlopi** [comment]
There are exciting news on this side, as in I have a test deployment where this works, but there is still work needed to integrate this in the shell and properly package this.

In the meantime, if you would like to be kept updated, I recommend to join https://discord.duckdb.org.

**Comment by mattijn** [comment]
Thanks for the prompt response! I'm looking forward. I've joined the discord to be kept updated; while being there saw this potential upcoming feature:
<img src="https://user-images.githubusercontent.com/5186265/225905778-f761414c-5cfd-42ce-9834-2c356434b7e8.png" width="500px">
Maybe something even more to look forward to;).

**Comment by carlopi** [comment]
Hi @mattijn, we have put up a very experimental deployment at https://shellwip.duckdb.org/ that include loading of extensions.

```
LOAD sqlite_scanner;
```
works, and functions appears to be exported, I don't see any particular blocker for this to work, but also has not been tested in any way, so hard to say.

It would be cool if you can give it a go and if you have any feedback.

Here (https://github.com/duckdb/duckdb-wasm-wip#readme) there are some explanations, current phase is understanding whether this path for extension loading is viable and works on fixing outstanding issues.

**Comment by carlopi** [comment]
I end up adding a catch-all issue about extension loading: https://github.com/duckdb/duckdb-wasm/issues/1202.

Join there or re-open when you have any feedback on extension loading, especially regarding sqlite_scanner.

**Comment by mattijn** [comment]
Thank you for the work! I'll add our feedback to the other issue once we have played a bit with this.
