### ISSUE TITLE
WASM Not working with Big Dataset

### ISSUE THREAD

**Issue by akash-goel** [duckdb/duckdb-wasm#1191]
Hi Team,

when we have loaded the 10000 records then count , Aggregation and if queries on WASM are working fine but when we are loading 10 miillion records with 16 column in WASM and performing count query or if query than browser giving alerts to wait or executing in 3-4 minutes .

Can you please guide with how many records WASM is working fine

i have tested this if query with 1 lakh rows and browser is taking long time and asking to wait .
`select passenger_count ,trip_distance,VendorID, CASE WHEN VendorID=='2' THEN passenger_count/trip_distance ELSE trip_distance/passenger_count END AS test FROM {0}`

**Comment by carlopi** [comment]
Could you potentially try your workload both in duckdb native AND duckdb-wasm and compare the slowdown?

And size of your data set it's also a relevant data point.

**Comment by carlopi** [comment]
Hi @akash-goel, could you provide any more information on the problem you are seeing?

There are many potential issues (and solutions) but it's hard to guess without more information.

**Comment by carlopi** [comment]
Hi @akash-goel, I am closing this for now, but should things not be working for you feel free to reopen with some additional info.

**Comment by cacious7** [comment]
I am facing this problem. When it comes to running queries on large dataset of at least 1million rows, it takes just too long and the browser crashes sometimes. And this is in a query where I am simply trying to change the column name of a table.

How do we fix this please or is there an optimum number of rows that are possible with duckdb wasm?
