### ISSUE TITLE
Duck Db giving issue on Angular

### ISSUE THREAD

**Issue by akash-goel** [duckdb/duckdb-wasm#1201]
Hi Team,

I am working on Duckdb wasm on Angular , I am getting below error , Can you please guide how to resolve this

**duckdb-browser-eh.worker.js:1 
Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.**

Please find the below code for your reference

 const DUCKDB_BUNDLES: duckdb.DuckDBBundles = {
    mvp: {
      mainModule: './duckdb-mvp.wasm',
      mainWorker: "./duckdb-browser-mvp.worker.js"
    },
    eh: {
      mainModule: './duckdb-eh.wasm',
      mainWorker: "./duckdb-browser-eh.worker.js"
    },
  };
  
  async initDB() {
      const bundle = await duckdb.selectBundle(DUCKDB_BUNDLES);
      const logger = new duckdb.ConsoleLogger();
      const worker = await new Worker(bundle.mainWorker!);
      const db = new duckdb.AsyncDuckDB(logger, worker);
  
      await db.instantiate(bundle.mainModule,bundle.pthreadWorker);
      const conn = await db.connect();
      dbInstance = db
      return db;
    }

**Comment by carlopi** [comment]
I read the error as the resource is not found, I would expect the browser network tab to show the resource being fetched from the wrong (relative) URL.
I can set up a test deployment so it can be used as a reference, but in the meantime could you have a look at these examples: https://github.com/duckdb-wasm-examples?

**Comment by akash-goel** [comment]
It was not recognizing the wasm type so written the interceptot to set application/wasm when reading wasm

Thank Team for your Support

**Comment by carlopi** [comment]
If you set up a basic skeleton in Angular, or if you have something publicly available, it would be probably cool to add it to a (not yet existing) list of project based on duckdb-wasm, that could be used as a reference for whoever comes next.

This list hasn't a place yet, but it would be probably nice to have.
