### ISSUE TITLE
PRAGMA version reports a wrong version in NPM version

### ISSUE THREAD

**Issue by kimmolinna** [duckdb/duckdb-wasm#1234]
### What happens?

PRAGMA version; reports version v0.0.1-dev0 for duckdb-wasm NPM version 1.24.0. Actually it does it since version 1.20 at least.

### To Reproduce

Go to shell.duckdb.org look what database says and then you can try command: `PRAGMA version;` and you will see the same thing.

### Browser/Environment:

It doesn't matter

### Device:

It doesn't matter

### DuckDB-Wasm Version:

1.20 ->

### DuckDB-Wasm Deployment:

shell.duckdb.org

### Full Name:

Kimmo Linna

### Affiliation:

F

**Comment by carlopi** [comment]
Thank you for raising this, I had mis-categorized this bug, but it's actually there already in the duckdb-wasm/packages/duckdb-wasm component. Simplest repro, basically from any kind of setup (node / browser / whatever) is:
```sql
select version()
```
that should mimic the native duckdb CLI in returning the underlying DuckDB version.
