### ISSUE TITLE
Wasm range request failure

### ISSUE THREAD

**Issue by taniabogatsch** [duckdb/duckdb-wasm#1235]
### What happens?

duckdb-wasm fails when requesting data from the GitHub API during range requests.

### To Reproduce

Go to https://shellwip.duckdb.org.
```sql
LOAD json;
SELECT * FROM read_json_auto('https://api.github.com/repos/duckdb/duckdb/commits?per_page=10000&foo.json');
```

```
Invalid Error: Error: Range request for https://api.github.com/repos/duckdb/duckdb/commits?per_page=10000&foo.json failed with error: Error: Range request for https://api.github.com/repos/duckdb/duckdb/commits?per_page=10000&foo.json did not return a partial response: 200 """
```

### Browser/Environment:

Safari Version 16.4

### Device:

MacBook Pro M1 2020

### DuckDB-Wasm Version:

1.11.0

### DuckDB-Wasm Deployment:

shellwip.duckdb.org

### Full Name:

Tania Bogatsch

### Affiliation:

DuckDB Labs

**Comment by carlopi** [comment]
This has been now fixed via #1236, builds are in progress.

Thanks!
