### ISSUE TITLE
numbers in a JSON field get parsed strangely

### ISSUE THREAD

**Issue by enjalot** [duckdb/duckdb-wasm#1267]
### What happens?

Numbers in JSON fields don't seem to be parsed correctly. Perhaps the schema isn't being interpreted properly?

### To Reproduce

After creating a parquet file with the following Python code:
```python
basictest = [
    {
        "msg_id": "1234",
        "somejson": {"hi": "there", "foo": 1024 }
    }
]
basictestdf = pd.DataFrame(basictest)
basictestdf.to_parquet("basictest.parquet")
```

We get unexpected value for `somejson.foo`, it should be 1024 but instead its 5.06e-321.
See web-based example: https://observablehq.com/d/c5f796070b98c2a5

However duckdb-cli gives the expected values:
```bash
D SELECT * from '~/Downloads/basictest.parquet';
┌─────────┬────────────────────────────────┐
│ msg_id  │            somejson            │
│ varchar │ struct(foo bigint, hi varchar) │
├─────────┼────────────────────────────────┤
│ 1234    │ {'foo': 1024, 'hi': there}     │
└─────────┴────────────────────────────────┘
```

### Browser/Environment:

Chrome 112

### Device:

Desktop

### DuckDB-Wasm Version:

not sure

### DuckDB-Wasm Deployment:

observablehq.com

### Full Name:

Ian Johnson

### Affiliation:

Latent Interfaces

**Comment by carlopi** [comment]
Hi @enjalot, thanks for the bug report!

I can't reproduce against duckdb-wasm's [shell](https://shell.duckdb.org), so this is likely this is tied either to some specific of Observable client or the fact that they are a not up with latest developments.

**Comment by enjalot** [comment]
It looks like Observable uses a kind of fork of duckdb-wasm so it probably is there. I also can see it works as expected in the shell.
https://github.com/observablehq/stdlib/blob/main/src/duckdb.js

I've submitted the issue with observable, thanks!
