### ISSUE TITLE
Loading extensions broken in node

### ISSUE THREAD

**Issue by whscullin** [duckdb/duckdb-wasm#1276]
### What happens?

Attempting to dynamically load an extension using duckdb-wasm under node fails in a few ways.

Executing the sequence
```
INSTALL icu
LOAD icu
```
first fails with
```
Error: IO Error: Can't find the home directory at '/home/web_user'
```
setting `home_directory` to `os.homedir()`, then gives:
```
Error [TypeError]: g_.getSocket is not a function
```

(Simply running `LOAD icu` tells you to install the extension)

### To Reproduce

Executing the sequence
```
INSTALL icu
LOAD icu
```
when using duckdb-wasm under node.

### Browser/Environment:

node v16.14.2

### Device:

MacBook Pro

### DuckDB-Wasm Version:

0.8.0

### DuckDB-Wasm Deployment:

Malloy

### Full Name:

Will Scullin

### Affiliation:

Google

**Comment by alukach** [comment]
See https://github.com/duckdb/duckdb-wasm/issues/1202

**Comment by carlopi** [comment]
I think this has been solved properly since https://github.com/duckdb/duckdb-wasm/pull/1544, could you give a try with the latest version?

Thanks a lot

**Comment by whscullin** [comment]
Just tried the latest, looks to be fixed. Thanks!
