### ISSUE TITLE
Is there any documentation on how to use the react-hooks subproject? 

### ISSUE THREAD

**Issue by edwinjue** [duckdb/duckdb-wasm#1280]
### What happens?

@ankoh  Using the react-hooks subproject, would be great if someone could show how to initialize a duckdb instance from a persistent file from a react component and output the result of a simple query like 'select count(*) from sometable' to the browser console.

If anyone knows how or can provide documentation, that would be great. Appreciate your efforts! Thanks 

### To Reproduce
Trying to do something like this:
https://gist.github.com/edwinjue/d06e12b1a351b9b3f31f770eea52a71e

### Browser/Environment:

Chrome

### Device:

Desktop web browser

### DuckDB-Wasm Version:

https://github.com/duckdb/duckdb-wasm/tree/master/packages/react-duckdb

### DuckDB-Wasm Deployment:

https://github.com/duckdb/duckdb-wasm/tree/master/packages/react-duckdb

### Full Name:

Edwin J

### Affiliation:

311-data

**Comment by edwinjue** [comment]
Thanks for your reply @ankoh. 

I was able to create a Hello World component from the other duckdb-wasm examples and output the response table to the browser console here: 

https://github.com/edwinjue/311-data-v2-gh-pages/blob/2d6faa1ffcbd68b2a809bc473451599b8ecf58d7/components/DuckDbHelloWorld.jsx#L27 

The next thing I need to do is seed the duckdb-wasm db instance with our csv data but I am a little lost because I wasn't able to find documentation to show us how to do so properly.

I saw this in the duckdb-wasm source code but I'm not sure if this is the interface used: https://github.com/duckdb/duckdb-wasm/blob/4b921631182bbe3bee20d29d3d69e346685bd030/packages/duckdb-wasm/src/parallel/async_bindings_interface.ts

```
//duckdb-wasm source code
insertArrowFromIPCStream(conn: number, buffer: Uint8Array, options?: CSVInsertOptions): Promise<void>;
insertCSVFromPath(conn: number, path: string, options: CSVInsertOptions): Promise<void>;
insertJSONFromPath(conn: number, path: string, options: JSONInsertOptions): Promise<void>;
```

I'm wondering to seed the db, should I call one of the above methods on the db instance somewhere here:
```
//my component
const db = new duckdb.AsyncDuckDB(logger, worker);
await db.instantiate(DUCKDB_CONFIG.mainModule, DUCKDB_CONFIG.pthreadWorker);
const conn = await db.connect();
```

Or is there a better way to do this? 

I am open to seeding the db with csv or parquet format. 

But if there is a way to connect directly to a preloaded and pre-existing persistent db file (e.g. - master.duckdb), that would be even better. 

Please let me know when you find some time. Much appreciated as always @ankoh 

Thanks

**Comment by edwinjue** [comment]
Hi @ankoh I was able to seed the db using a parquet file:

https://github.com/edwinjue/311-data-v2-gh-pages/blob/duckdb-wasm-DuckDbHelloWorld/components/DuckDbHelloWorld.jsx

If there is a better way, please let me know. Thanks in advance!

**Comment by edwinjue** [comment]
@ankoh just wanted to follow up to let you know I was able to get everything going. feel free to take a look. this is another real world use case for duckdb-asm: https://github.com/edwinjue/311-data-v2-gh-pages

**Comment by codering** [comment]
I tried using hooks in this way, and it works.

```jsx
import {
  useDuckDBConnection,
  useDuckDBConnectionDialer,
} from "@duckdb/react-duckdb";
import { useEffect } from "react";

export default function HomePage() {
  const connDialer = useDuckDBConnectionDialer();
  const conn = useDuckDBConnection();
  useEffect(() => {
    if (conn?._conn) {
      console.log("db connected", conn);
      return;
    }
    const load = async () => await connDialer();
    load();
  }, [conn]);
  return <></>
}
```

**Comment by edwinjue** [comment]
oh wow, thank you so much for this! i will definitely take a look. do you mind me asking whether there was an example or documentation you extracted this from? and whether you have the links to those resources? much appreciated! @codering

**Comment by codering** [comment]
@edwinjue Translation: I couldn't find any documentation either. When I first searched this code https://stackoverflow.com/q/73026431, I still didn't know how to obtain the connection. So, I looked at the source code of react-duckdb, and then I wrote this custom hook myself.
