### ISSUE TITLE
Error sort query with array of struct type

### ISSUE THREAD

**Issue by handstuyennn** [duckdb/duckdb-wasm#1298]
### What happens?

I built duckdb shell from latest code of duckdb-wasm.
I ran following queries and found got error `memory access out of bounds`:

- `CREATE TABLE  test (id integer PRIMARY KEY,struct_arr ROW(val1 integer, val2 varchar)[],);`
- `INSERT INTO test VALUES (1, [(1, 'test'), (2, 'lorem ipsum')]), (2, [(3, 'dolor'), (4, 'sit')])`
- `SELECT * FROM test ORDER BY id DESC;`

### To Reproduce
Start duckdb shell in browser with command `make app_start`
Run following query in duckdb wasm shell:

> CREATE TABLE  test (id integer PRIMARY KEY,struct_arr ROW(val1 integer, val2 varchar)[],);

> INSERT INTO test VALUES (1, [(1, 'test'), (2, 'lorem ipsum')]), (2, [(3, 'dolor'), (4, 'sit')]);

> SELECT * FROM test ORDER BY id DESC;

### Browser/Environment:

Chrome

### Device:

MacOS

### DuckDB-Wasm Version:

latest code from branch `master`

### DuckDB-Wasm Deployment:

http://localhost:9002/

### Full Name:

Tuyen Nguyen Ngoc

### Affiliation:

Developer

**Comment by carlopi** [comment]
Hi @handstuyennn! I am not sure I understand what might be happening, since in theory you should get the same results between master and shell.

Could you try once again from a fresh folder following the instructions here: https://github.com/duckdb/duckdb-wasm#build-from-source?

**Comment by handstuyennn** [comment]
Yes, I build exactly following the instructions in this file.
After that I ran command `make app_start`
And here is what I get in my browser.

![image](https://github.com/duckdb/duckdb-wasm/assets/49063786/cf605685-a3c5-4193-a8a1-879e4456ab0f)

**Comment by carlopi** [comment]
Thanks for raising this, I do reproduce, I guess one big problem is that this path is not really tested, so this somehow slipped.

I will ping when I have fix, and I will make so that the default configuration should be tested regularly by CI (as to catch regression earlier).

**Comment by carlopi** [comment]
Hey! I tracked this down to stack-overflow, due to a combinations of three factors: there is less stack that usual in WebAssembly (and less memory in general), there was a potentially problematic stack-allocated big-structure in duckdb, and the default is building using no optimizations, that it's not really usual (or at least, helps in putting different problems under the lens).

1 is unavoidable, 2 will be reviewed, but 3 it's both easy and makes sense as a change. Fill file in a PR soon.
