### ISSUE TITLE
Nonsensical formatting of intervals in duckdb wasm shell at https://shell.duckdb.org/

### ISSUE THREAD

**Issue by bcolloran** [duckdb/duckdb-wasm#1348]
### What happens?

at https://shell.duckdb.org/, enter the following:
```
duckdb> (select interval '1 years' as intvl);
┌────────────────────────────────────────────────┐
│ intvl                                          │
╞════════════════════════════════════════════════╡
│ 0 years 0 mons 0 days 0 hours 0 mins 0.12 secs │
└────────────────────────────────────────────────┘
Elapsed: 1 ms
```

### To Reproduce

at https://shell.duckdb.org/, enter the following:
```
duckdb> (select interval '1 years' as intvl);
┌────────────────────────────────────────────────┐
│ intvl                                          │
╞════════════════════════════════════════════════╡
│ 0 years 0 mons 0 days 0 hours 0 mins 0.12 secs │
└────────────────────────────────────────────────┘
Elapsed: 1 ms
```

### Browser/Environment:

firefox 115.0.3

### Device:

thinpad x1

### DuckDB-Wasm Version:

 @duckdb/duckdb-wasm@1.27.1-dev59.0

### DuckDB-Wasm Deployment:

https://shell.duckdb.org/

### Full Name:

bcolloran

### Affiliation:

Rill Data

**Comment by Y--** [comment]
Hi Brendan! 

I think the issue is that DuckDB WASM isn't compiled with the [ICU](https://duckdb.org/2022/01/06/time-zones.html) extension by default.
It seems to work on DuckDB WASM that do enable the extension:
![image](https://github.com/duckdb/duckdb-wasm/assets/773683/21decdf9-4b4e-4a15-b472-18a438d89390)

**Comment by carlopi** [comment]
This can also be solved, due to arrow-rust having solved this problem upstream. See https://github.com/duckdb/duckdb-wasm/pull/1769
