### ISSUE TITLE
Can't install and load spatial extension

### ISSUE THREAD

**Issue by nshiab** [duckdb/duckdb-wasm#1542]
### What happens?

When trying to reproduce the example from [Extension for DuckDB-Wasm](https://duckdb.org/2023/12/18/duckdb-extensions-in-wasm.html), I couldn't install and load the spatial extension.

Here's the error:
```
async_bindings.ts:150 Uncaught Error: IO Error: Extension "/home/web_user/.duckdb/extensions/v0.9.1/wasm_eh/spatial.duckdb_extension" not found.
Extension "spatial" is an existing extension.

Install it first using "INSTALL spatial".
```

### To Reproduce

Here's the code I used. You can copy and paste it into an HTML file and open it with a browser.

```html
<!DOCTYPE html>
<html>
  <body>
    <script type="module">
      import * as duckdb from "https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.28.0/+esm";

      const JSDELIVR_BUNDLES = duckdb.getJsDelivrBundles();

      // Select a bundle based on browser checks
      const bundle = await duckdb.selectBundle(JSDELIVR_BUNDLES);

      const worker_url = URL.createObjectURL(
        new Blob([`importScripts("${bundle.mainWorker}");`], {
          type: "text/javascript",
        })
      );

      // Instantiate the asynchronus version of DuckDB-wasm
      const worker = new Worker(worker_url);
      const logger = new duckdb.ConsoleLogger();
      const db = new duckdb.AsyncDuckDB(logger, worker);
      await db.instantiate(bundle.mainModule, bundle.pthreadWorker);
      URL.revokeObjectURL(worker_url);

      const conn = await db.connect();
      await conn.query(`INSTALL spatial; LOAD spatial;`);
    </script>
  </body>
</html>

```

### Browser/Environment:

Version 120.0.6099.109 (Official Build) (arm64)

### Device:

MacBoork PRO m1

### DuckDB-Wasm Version:

1.28.0

### DuckDB-Wasm Deployment:

html page

### Full Name:

Nael Shiab

### Affiliation:

CBC/Radio-Canada

**Comment by domoritz** [comment]
The shell is using `@duckdb/duckdb-wasm@1.28.1-dev59.0`. Extension support is pretty new so try the latest version.

**Comment by nshiab** [comment]
Thanks, @domoritz ! But it doesn't look like it's available on npm for now. I guess I am too impatient! It's a great addition to be able to use extensions. :)

https://www.npmjs.com/package/@duckdb/duckdb-wasm?activeTab=versions

**Comment by carlopi** [comment]
I need to review why CI had not pushed a new version on npm, I will update when it's out.

**Comment by carlopi** [comment]
Can you give it a try with the latest package on npm: `1.28.1-dev65.0`?

It should work while hosting it locally.

**Comment by nshiab** [comment]
Hi!

So...

- According to the readme, we should use [this URL to manually download the files](https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm/dist/) but jsdelivr returns this message on the page: _Package size exceeded the configured limit of 150 MB_. Should I use another URL?

- Same thing with:
  -  https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.28.1-dev65.0/+esm
  -  https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.28.1-dev75.0/+esm (latest according to your page on npm)

I guess something went wrong when publishing on npm...

**Comment by tobilg** [comment]
I checked this on npm as well, 1.28.0 is 71.9 MB (https://www.npmjs.com/package/@duckdb/duckdb-wasm/v/1.28.0), 1.28.1-dev65.0 is 1.63 GB which is more than 20 times as much. 

Seems like this can't be correct even with more exposed functions...

**Comment by carlopi** [comment]
I think this should be solved, jsdelivr is back online: https://www.jsdelivr.com/package/npm/@duckdb/duckdb-wasm.

Serving this file works now as intended (no errors shown):
```html
<!DOCTYPE html>
<html>
  <body>
    <script type="module">
      import * as duckdb from "https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.28.1-dev91.0/+esm";

      const JSDELIVR_BUNDLES = duckdb.getJsDelivrBundles();

      // Select a bundle based on browser checks
      const bundle = await duckdb.selectBundle(JSDELIVR_BUNDLES);

      const worker_url = URL.createObjectURL(
        new Blob([`importScripts("${bundle.mainWorker}");`], {
          type: "text/javascript",
        })
      );

      // Instantiate the asynchronus version of DuckDB-wasm
      const worker = new Worker(worker_url);
      const logger = new duckdb.ConsoleLogger();
      const db = new duckdb.AsyncDuckDB(logger, worker);
      await db.instantiate(bundle.mainModule, bundle.pthreadWorker);
      URL.revokeObjectURL(worker_url);

      const conn = await db.connect();
      await conn.query(`INSTALL spatial; LOAD spatial;`);
    </script>
  </body>
</html>
```

**Comment by carlopi** [comment]
Thanks for the patience, and see the discussion here: https://github.com/duckdb/duckdb-wasm/issues/1561 for more background informations.

**Comment by nshiab** [comment]
Wonderful! Thanks, @carlopi!
