### ISSUE TITLE
Support custom expressions

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb-wasm#159]
It would be great to support e.g. js expressions in DuckDB so that one can write (for now synchronous) code to compute some derived value. Maybe we could even support user defined aggregates. 

As we discussed before, supporting async code would be pretty trick since we can't just stop and reenter the execution in wasm right now. Maybe DuckDB will add async execution in the future to support async expressions as well.

**Comment by ankoh** [comment]
We support synchronous UDFs written in JavaScript now.

**Comment by keller-mark** [comment]
Can you elaborate on would be needed to support `createScalarFunction` for `AsyncDuckDB`?
