### ISSUE TITLE
Use @next tag for development releases (keeping @latest more stable)

### ISSUE THREAD

**Issue by carlopi** [duckdb/duckdb-wasm#1591]
This problem is affecting the latest release on npm, e.g.:

https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm/+esm

I’m wondering if you intended to make 1.28.1-dev82.0 the current release (@latest tag), or if you intended for this to be a prerelease? Because this version still works:

https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.28.0/+esm

If you intend these to be prereleases, I’d recommend publishing them to the next tag, say using `npm publish --tag next`. (I wrote a [guide on this](https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420) some years back.)

_Originally posted by @mbostock in https://github.com/duckdb/duckdb-wasm/issues/1561#issuecomment-1888346358_

**Comment by mbostock** [comment]
To repoint the @latest tag back at the last stable release (1.28.0 instead of 1.28.1-dev99.0), you can run this command:

```
npm dist-tag add @duckdb/duckdb-wasm@1.28.0 latest
```
