### ISSUE TITLE
Please repoint the latest npm dist-tag to 1.28.0 instead of 1.28.1-dev106.0

### ISSUE THREAD

**Issue by mbostock** [duckdb/duckdb-wasm#1661]
### What happens?

When installing DuckDB as `npm install @duckdb/duckdb-wasm`, I currently get the `latest` tag which points to `1.28.1-dev106.0`, which is an old prerelease. I expect instead to get the latest stable release which is currently `1.28.0`. (If I want to install the latest prerelease, I can say `npm install @duckdb/duckdb-wasm@next` which correctly points to `1.28.1-dev159.0`.)

To fix this, a maintainer needs to re-point the `latest` tag to `1.28.0` by running this command:

```
npm dist-tag add @duckdb/duckdb-wasm@1.28.0 latest
```

Previously suggested https://github.com/duckdb/duckdb-wasm/issues/1591#issuecomment-1908595801.

### To Reproduce

```
npm install @duckdb/duckdb-wasm
```

### Browser/Environment:

npm

### Device:

macOS

### DuckDB-Wasm Version:

N/A

### DuckDB-Wasm Deployment:

N/A

### Full Name:

Mike Bostock

### Affiliation:

Observable

**Comment by carlopi** [comment]
I think this can be considered closed, duckdb-wasm is now out on version 1.29.0 with proper tag.

Moving forward we will avoid this problems, thanks a lot for proposing this. Can you possibly check whether this works on your end? Thanks a lot

**Comment by mbostock** [comment]
Yep, works great now. Thank you!

**Comment by mootari** [comment]
@carlopi I'm afraid it's happened again. 1.29.1-dev132.0 is tagged as [latest](https://www.npmjs.com/package/@duckdb/duckdb-wasm/v/latest).
