### ISSUE TITLE
No repr shown for Maps

### ISSUE THREAD

**Issue by NickCrews** [duckdb/duckdb-wasm#1671]
### What happens?

Try these queries on shell.duckdb.org:

```sql
SELECT MAP(['key1', 'key2', 'key3'], [10, 20, 30]);
SELECT MAP([], []);
SELECT MAP(NULL::INT[], NULL::INT[]);
```
none of them show any output.

But, if you run these in another client, such as the CLI or python, then you see the result (although the NULL case is incorrect due to the unrelated https://github.com/duckdb/duckdb/issues/11115)

### To Reproduce

above

### Browser/Environment:

chrome 122.0.6261.94 (Official Build) (arm64)

### Device:

2021 macbook M1 Max

### DuckDB-Wasm Version:

@duckdb/duckdb-wasm@1.28.1-dev166.0

### DuckDB-Wasm Deployment:

shell.duckdb.org

### Full Name:

Nick Crews

### Affiliation:

Ship Creek Group

**Comment by carlopi** [comment]
This is fixed by https://github.com/duckdb/duckdb-wasm/pull/1769, thanks to bumping arrow-rust that now supports maps

**Comment by carlopi** [comment]
Merged, this can be closed, thanks
