### ISSUE TITLE
Docker Image uses a non-compatible version of Emscripten (3.1.24) which makes build to fail

### ISSUE THREAD

**Issue by jcolot** [duckdb/duckdb-wasm#1680]
### What happens?

The build fails from the Docker image because of an outdated version of Emscripten (3.1.24). Since 3.1.45, the function used to add symbols the JS library has been renamed from `mergeInto`, to `addToLibrary` [Changelog](https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3145---082323). Further, fixing this the build also fails for an out-of-date Rust and missing ENV value for `CHROME_BIN`

### To Reproduce

Build the container, and run make from inside

`docker run --rm -v .:/wd <image_name>:<tag> make`

### Browser/Environment:

NA

### Device:

NA

### DuckDB-Wasm Version:

1.28.0

### DuckDB-Wasm Deployment:

NA

### Full Name:

Julien Colot

### Affiliation:

Jetpack.AI

**Comment by carlopi** [comment]
Solved by https://github.com/duckdb/duckdb-wasm/pull/1681
