### ISSUE TITLE
Error loading spatial extension in duckdb shell

### ISSUE THREAD

**Issue by kbatchu** [duckdb/duckdb-wasm#1713]
### What happens?

When I try to load the 'spatial' extension in the DuckDB shell, I get the following error message "Invalid Input Error: Initialization function "spatial_init" from file "https://extensions.duckdb.org/v0.10.2/wasm_eh/spatial.duckdb_extension.wasm" threw an exception: "/MAX/SUM/AVG/COUNT implementation"

### To Reproduce

In the Duckdb shell i.e. https://shell.duckdb.org/, try to load the spatial extension.

### Browser/Environment:

Microsoft Edge Version 123.0.2420.97

### Device:

Windows desktop

### DuckDB-Wasm Version:

duckdb-wasm@1.28.1-dev181.0

### DuckDB-Wasm Deployment:

duckdb-wasm@1.28.1-dev181.0

### Full Name:

KiranKumar Batchu

### Affiliation:

Personal

**Comment by carlopi** [comment]
This should be now fixed, but there might be some caching still going on, refreshing the browser-tab should help.

Try: https://shell.duckdb.org/#queries=v0,LOAD-spatial
