### ISSUE TITLE
Build error on 'main' branch

### ISSUE THREAD

**Issue by ivan-tkatchev** [duckdb/duckdb-wasm#1765]
### What happens?

```
[ 95%] Building CXX object CMakeFiles/duckdb_web.dir/src/webdb_api.cc.o
/build/source/lib/src/io/web_filesystem.cc:648:78: error: 'flags' is a private member of 'duckdb::FileOpenFlags'
  648 |                 auto *opened = duckdb_web_fs_file_open(file->file_id_, flags.flags);
      |                                                                              ^
/build/source/build/relperf/mvp/third_party/duckdb/install/include/duckdb/common/file_open_flags.hpp:104:8: note: declared private here
  104 |         idx_t flags = 0;
      |               ^
1 error generated.
```

### To Reproduce

Any attempt to build will fail, see error message.

### Browser/Environment:

none

### Device:

none

### DuckDB-Wasm Version:

main

### DuckDB-Wasm Deployment:

none

### Full Name:

Ivan Tkachev

### Affiliation:

Hyper AdTech

**Comment by carlopi** [comment]
Hi! This I need to fix at the Makefile level, at the moment you need to do something like:
```
patch -p1 -d submodules/duckdb < cat duckdb.patch
```
or equivalent
```
cd submodules/duckdb
git apply ../../duckdb.patch
cd ../..
```
before building.

**Comment by attila-kun** [comment]
Before building, I did `make patch_duckdb`, then it worked.

**Comment by carlopi** [comment]
I think this should be solved now, at the moment you need `make apply_patches`
