### ISSUE TITLE
(shell.duckdb.org) ST_Read on GeoJson results in GDAL Error - Unexpected character (

### ISSUE THREAD

**Issue by prusswan** [duckdb/duckdb-wasm#1830]
### What happens?

ST_Read on a common GeoJson test file results in GDAL Error - Unexpected character (

### To Reproduce

`SELECT * FROM ST_Read('https://raw.githubusercontent.com/ibis-project/testing-data/master/geojson/zones.geojson');`

![image](https://github.com/user-attachments/assets/2dbb5599-5659-4ffa-bdb8-e0dcf1e7a03d)

### Browser/Environment:

Firefox 126.0.1

### Device:

laptop

### DuckDB-Wasm Version:

1.28.1-dev258.0

### DuckDB-Wasm Deployment:

shell.duckdb.org

### Full Name:

Pruss Wan

### Affiliation:

none

**Comment by szarnyasg** [comment]
Hi @prusswan – thanks for opening this. Try loading the `httpfs` extension as well, this works around the problem for me:

```sql
LOAD httpfs;
```

Of course, the error message could be improved.

**Comment by prusswan** [comment]
> Hi @prusswan – thanks for opening this. Try loading the `httpfs` extension as well, this works around the problem for me:
> 
> ```sql
> LOAD httpfs;
> ```
> 
> Of course, the error message could be improved.

Still happens for me. I guess I will try with a more stable WASM version until this gets resolved.

![image](https://github.com/user-attachments/assets/b12b1203-fda8-4f39-8c8a-f5e90d133379)

**Comment by carlopi** [comment]
I believe this to be solved in the latest duckdb/duckdb-wasm/spatial version.

Please check: https://shell.duckdb.org/#queries=v0,LOAD-spatial~,CREATE-TABLE-T-AS-FROM-ST_Read('https%3A%2F%2Fraw.githubusercontent.com%2Fibis%20project%2Ftesting%20data%2Fmaster%2Fgeojson%2Fzones.geojson')~,DESCRIBE-T~,SELECT-count(*)-FROM-T~

Or the equivalent SQL:
```sql
--- httpfs loading is necessary in native, while not working on wasm, we need to better align the two versions here
LOAD httpfs;
LOAD spatial;
CREATE TABLE T AS FROM ST_Read('https://raw.githubusercontent.com/ibis-project/testing-data/master/geojson/zones.geojson');
DESCRIBE T;
SELECT count(*) FROM T;
```

This is:
```
DuckDB Web Shell
Database: v1.1.1
Package:  @duckdb/duckdb-wasm@1.28.1-dev288.0
```
