### ISSUE TITLE
ATTACH remote database doesn't work anymore

### ISSUE THREAD

**Issue by tobilg** [duckdb/duckdb-wasm#1868]
### What happens?

Is it possible that attaching databases no longer work in in the latest dev versions? When running `ATTACH 'https://raw.githubusercontent.com/tobilg/aws-iam-data/main/data/db/iam.duckdb' as aws_iam (READ_ONLY);`, I see the following error: 

```text
Error: IO Error: Extension https://extensions.duckdb.org/v1.1.0/wasm_eh/httpfs.duckdb_extension.wasm is not available. 
```

Accessing other files via http seems to work though. When trying to access https://extensions.duckdb.org/v1.1.0/wasm_eh/httpfs.duckdb_extension.wasm I see a 403 error

`v258` which is `v1.0.0` works with ATTACH statements. I tried a lot of newer versions, without success... 

### To Reproduce

Try this in the Shell:

https://shell.duckdb.org/#queries=v0,ATTACH-'https%3A%2F%2Fraw.githubusercontent.com%2Ftobilg%2Faws%20iam%20data%2Fmain%2Fdata%2Fdb%2Fiam.duckdb'-as-aws_iam-(READ_ONLY)~,load-httpfs~

### Browser/Environment:

Chrome latest

### Device:

MacBookPro

### DuckDB-Wasm Version:

1.28.1-dev287.0

### DuckDB-Wasm Deployment:

shell.duckdb.org

### Full Name:

Tobi M.

### Affiliation:

None

**Comment by carlopi** [comment]
I think this is now working, can you possibly give it a try?

(fix was making sure `httpfs` extensions was build and deployed in the right spot)

**Comment by tobilg** [comment]
Thanks, I just checked via https://shell.duckdb.org/#queries=v0,ATTACH-'https%3A%2F%2Fraw.githubusercontent.com%2Ftobilg%2Faws%20iam%20data%2Fmain%2Fdata%2Fdb%2Fiam.duckdb'-as-aws_iam-(READ_ONLY)~ and it works now.
