### ISSUE TITLE
Add S3FS

### ISSUE THREAD

**Issue by ankoh** [duckdb/duckdb-wasm#251]
```SELECT * FROM parquet_scan('s3://<bucket>/<file>');```

Would be a pretty sweet example.
Mostly building [this](https://github.com/duckdb/duckdb/blob/master/extension/httpfs/httpfs.cpp) on top of our buffered filesystem.

**Comment by david542542** [comment]
@ankoh how would permissions work on this? For example, would this read from [`~/.aws/credentials`](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html) file, need to be entered in to the client, or only work on public buckets/files?

**Comment by ankoh** [comment]
We should definitely include private buckets.
But we cannot really read from the file without prompting the user.

I'd favor a method like
```ts
await db.setEnvironment({
  s3_region: 'es-east-1',
  s3_access_key_id='<AWS access key id>',
  s3_secret_access_key='<AWS secret access key>',
});
```

**Comment by Y--** [comment]
Wouldn't the `SET` work as well like in [this example](https://github.com/duckdb/duckdb/blob/f9e6e867554ec977a2e2c7f3c8e9b9a404588753/test/sql/copy/parquet/test_parquet_remote.test#L73)?

**Comment by ankoh** [comment]
Sure, we should support that as well.

**Comment by ankoh** [comment]
Added in https://github.com/duckdb/duckdb-wasm/pull/557
