### ISSUE TITLE
The example of loading JSON text in the README fails

### ISSUE THREAD

**Issue by llimllib** [duckdb/duckdb-wasm#334]
The README gives (after #333):

```
await db.registerFileText(
    'rows.json',
    `[
    { “col1”: 1, “col2”: “foo” },
    { “col1”: 2, “col2”: “bar” },
]`,
);
await db.insertJSONFromPath('rows.json', { name: 'test' });
```

But, when I run that, I get `TypeError: t is undefined`:

```
Uncaught (in promise) TypeError: t is undefined
    insertJSONFromPath http://devd.io:8000/dist/viewer_duckdb.js:11833
    <anonymous> debugger eval code:6
    async* debugger eval code:9
```

I created a [repository that reproduces the problem](https://github.com/llimllib/duckdb-wasm-repro), you can just clone it and open up index.html in a browser to see it in action

**Comment by ankoh** [comment]
Thanks! This is a typo in the README.

Insertion requires a connection:
```
// ..., from JSON documents in row-major format
await db.registerFileText(
    'rows.json',
    `[
    { “col1”: 1, “col2”: “foo” },
    { “col1”: 2, “col2”: “bar” },
]`,
);
// ... or column-major format
await db.registerFileText(
    'columns.json',
    `{
    “col1”: [1, 2],
    “col2”: [“foo”, “bar”]
}`,
);
// ... with typed insert options
await c.insertJSONFromPath('rows.json', { name: 'rows' });
await c.insertJSONFromPath('columns.json', { name: 'columns' });
```

I added a test with the README examples:
https://github.com/duckdb/duckdb-wasm/blob/d3e8d8fbb2fb23b1b82773f524fcf3587e2447a7/packages/duckdb-wasm/test/readme_examples.test.ts

Feel free to reopen the issue if the problem persists.
