### ISSUE TITLE
export database error

### ISSUE THREAD

**Issue by luckyfanghe** [duckdb/duckdb-wasm#340]
Hi. I am using duckdb-wasm in pure javascript.

Refered to https://observablehq.com/@cmudig/duckdb?collection=@cmudig/duckdb .

when i use export database '/out/localdb', i am getting error: "Not implemented Error: BufferedFileSystem: DirectoryExists is not implemented!".

Please give me solution.

**Comment by ankoh** [comment]
We do not yet support file exporting in DuckDB-wasm. This is very useful to have and should be added soon!

**Comment by ankoh** [comment]
Related to #105

**Comment by luckyfanghe** [comment]
Hope to be added soon. Thank you.

**Comment by david542542** [comment]
@ankoh Oh yea, that would be a fantastic feature to add. Is this something that needs to be added on the C++ front or more with the javascript-binding side?

**Comment by luckyfanghe** [comment]
@ankoh I am gonna update duckdb to export database. can you give me any document or tip for it?

**Comment by ankoh** [comment]
Sorry, I'm a bit loaded right now. I'll take a look at it a few hours today.
It's an interplay between C++ and TS, leaning more towards C++.

**Comment by luckyfanghe** [comment]
Can i save parquet files to local in browser?

**Comment by ankoh** [comment]
I added preliminary support for database exports in c6d64b55d116daefe1e848546da29aaf955db54d .
This test exports a database as parquet file and scans it afterwards:
https://github.com/duckdb/duckdb-wasm/blob/e0fc23dfa834a3a3c37bed02046daad9d002cf40/packages/duckdb-wasm/test/filesystem.test.ts#L212-L240

**Comment by ankoh** [comment]
It is not yet really exposed in the shell, that one has to be added separately.

**Comment by ankoh** [comment]
Please try it out in 0.1.12-dev54.0 and tell us how it's going, so that we can close this issue.

**Comment by david542542** [comment]
@ankoh is it possible to test this one out in the shell (I think not as per your last comment), for example trying:

```
DuckDB Web Shell
Database: v0.3.1-dev535
Package:  @duckdb/duckdb-wasm@0.1.12-dev56.0

Connected to a transient in-memory database.
Enter .help for usage hints.

duckdb> EXPORT DATABASE '/tmp/duckdbexportparquet' (FORMAT PARQUET);
┌┐
└┘

duckdb> CREATE TABLE foo AS SELECT * FROM generate_series(1, 5) t(v);
┌───────┐
│ Count │
╞═══════╡
│     5 │
└───────┘

duckdb> select * from foo;
┌───┐
│ v │
╞═══╡
│ 1 │
│ 2 │
│ 3 │
│ 4 │
│ 5 │
└───┘

duckdb> EXPORT DATABASE '/tmp/duck.parquet' (FORMAT PARQUET);
┌┐
```

It 'seems' to work, but in checking my actual filesystem I don't see anything there (I've tried a few variations of the above as well).

**Comment by luckyfanghe** [comment]
I am using pure js and refer to it.
https://observablehq.com/@cmudig/duckdb?collection=@cmudig/duckdb .
when i change libraryVersion = "0.1.12-dev54.0", getting the error (duckdb = Error: [Package Error] "apache-arrow" no dependency version info found.)

**Comment by domoritz** [comment]
This issue will be fixed when Arrow releases Arro 6.0.1

**Comment by david542542** [comment]
@domoritz I see, and it looks like their cadence is about once every two months or so -- https://arrow.apache.org/release/ -- which would probably be sometime in December or so? Any idea if that particular issue has been fixed or if it's still part of the TODOs for the 6.0.1 release? https://issues.apache.org/jira/projects/ARROW/issues/

**Comment by domoritz** [comment]
No, the 6.0.1 release should be sooner. Major releases are every three months but patch releases just need to go through a process on the mailing list. The fix is already in master and tagged for 6.0.1.

**Comment by luckyfanghe** [comment]
> 
> 
> The feature is not yet available in the shell but the following will already work:
> 
> <img alt="Screenshot 2021-11-08 at 21 59 21" width="1219" src="https://user-images.githubusercontent.com/3986510/140817247-e8be8616-e04e-4350-88f4-b83a0eb54b6d.png">
> 
> I have to list the files with the .files command in the shell and trigger a "Save As" prompt. I'll do that at the weekend.

**Comment by ankoh** [comment]
You cannot yet. At least not in the shell.
The API contains the method [copyFileToBuffer](https://shell.duckdb.org/docs/classes/index.AsyncDuckDB.html#copyFileToBuffer) which copies the file content to a Unit8Array but this is not (yet) available in the shell.
I'll add it at the weekend.

**Comment by david542542** [comment]
@ankoh @domoritz I was excited to see a new release earlier today. Does this new release cover the recent https://www.npmjs.com/package/apache-arrow 6.0.1?

**Comment by domoritz** [comment]
Yes. It includes https://github.com/duckdb/duckdb-wasm/commit/393bb612fa39e870ef63f165e390e27e7acd2779.

**Comment by david542542** [comment]
@ankoh @luckyfanghe can this item be closed now?

**Comment by ankoh** [comment]
It includes the ref to writing + [copyFileToBuffer](https://shell.duckdb.org/docs/classes/index.AsyncDuckDB.html#copyFileToBuffer) so I'll leave it in Just shipped for now.
We can track the export via shell command in a separate issue.
