### ISSUE TITLE
Allow user to override range requirement

### ISSUE THREAD

**Issue by llimllib** [duckdb/duckdb-wasm#342]
relates to #157 

In development, I use [devd](https://github.com/cortesi/devd/issues/42), which does not support range requests, and have a small data set. It would be very useful for me to be able to disable the range support requirement while I'm in development; my production server supports them.

The [inability to turn this off](https://github.com/duckdb/duckdb-wasm/blob/dc65c71e5c19e2aa36a4f4d11ed3ccbc28a04bbf/packages/duckdb-wasm/src/bindings/runtime_browser.ts#L58) means if I want to use duckdb-wasm, I have to rewrite my whole development setup.

**Comment by ankoh** [comment]
I understand your point. I was just not quite sure about the negative effects of a default fallback to non-ranged fetches.
The problem is, that duckdb-wasm runs in a web worker.
So if your user expects ranged reads and we would fallback to full reads for whatever reason, we might end up blocking duckdb database until the entire file is downloaded.
This is quite problematic especially for large files.

**Comment by ankoh** [comment]
It is non-trivial to abort downloading such a file once we started. We can terminate the web worker but thats about it (without SharedArrayBuffers).
This will change as soon as DuckDB gets fully async I/O but that's not possible today.

**Comment by ankoh** [comment]
We could add something like `allowFullReads` to the [DuckDBConfig](https://github.com/duckdb/duckdb-wasm/blob/06fd708bd33b6d2607c896cdf6d86a4328379e6a/packages/duckdb-wasm/src/bindings/config.ts) that defaults to false, for now.

**Comment by llimllib** [comment]
that would be the ideal solution for me, if it doesn't make sense overall feel free to close this though

**Comment by ankoh** [comment]
@llimllib Please try version 0.1.12-dev26.0 , it automatically falls back to full requests.
We only log a warning to the console for now.

**Comment by ankoh** [comment]
<img width="1242" alt="Screenshot 2021-11-03 at 23 50 03" src="https://user-images.githubusercontent.com/3986510/140233042-36fe5bd3-20c2-4af8-b236-99ed32e8df7d.png">

Neat side effect:
The shell can now read files from servers that dont include `range` in the CORS header `Access-Control-Allow-Headers.

**Comment by llimllib** [comment]
Can confirm it works, thank you very much!

![image](https://user-images.githubusercontent.com/7150/140236153-484e196d-a12f-48b0-b8bf-772d1c505498.png)
