### ISSUE TITLE
how to run SQL in https://shell.duckdb.org/

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb-wasm#373]
I input some words and press Enter, all words disappear

**Comment by ankoh** [comment]
What browser (+ version) are you using?
Ending a statement with a semicolon and pressing enter should execute the command.

**Comment by ankoh** [comment]
https://user-images.githubusercontent.com/3986510/141122909-99055c47-a16f-4b85-bae8-fdba16420d68.mp4

**Comment by l1t1** [comment]
thanks.  I used a Android brower on my phone. 
![Screenshot_20211111_063051_com huawei browser](https://user-images.githubusercontent.com/23301704/141204646-3067bcc2-1eab-470a-a4bb-b20395e6a513.jpg)

**Comment by l1t1** [comment]
I visit the site with my PC brower, the same problem. 
![shell_duckdb_2021-11-11_083942](https://user-images.githubusercontent.com/23301704/141216893-a98d3c68-5978-4f0d-bd9f-b67307114c89.png)

**Comment by l1t1** [comment]
ms edge 95 can run it. 
![2021-11-11_085929](https://user-images.githubusercontent.com/23301704/141218275-d52d7c96-afd1-4523-99b4-b7a816f6b597.png)

**Comment by ankoh** [comment]
WebAssembly ist still very young and we cannot really support older browser versions an non-mainstream browsers.
We should get better on the error reporting in the shell though since there likely will be an error printed to the console.
It should be visible in the shell.

Related to #110 .

**Comment by ankoh** [comment]
Closing this for now since we're currently targeting main-stream browsers.
