### ISSUE TITLE
some buttons is disabled when run .files command

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb-wasm#377]
the local file button is ok. 

the http files button 
and '-' button at the right of uploaded local file
are disabled.

**Comment by ankoh** [comment]
Yes that is true. The file dialog will be replaced with dedicated commands like `.files add, .files download` soon.

**Comment by ankoh** [comment]
The file command no longer open an overlay and now support:
```
.files list            List all files.
.files add             Add files.
.files download $FILE  Download a file.
.files drop            Drop all files.
.files drop $FILE      Drop a single file.
```
