### ISSUE TITLE
insertArrowTable on Observable

### ISSUE THREAD

**Issue by enjalot** [duckdb/duckdb-wasm#402]
I'm trying to use `insertArrowTable` in Observable, and I suspect that I'm requiring an incompatible version of apache-arrow:
https://observablehq.com/d/0288d022d3766866

I get this message when I try:
`Error: Unrecognized Message header: Schema<{ 0: precipitation: Float32, 1: date: Date64<MILLISECOND> }>`

Is the arrow used by duckdb-wasm accessible from outside?

**Comment by ankoh** [comment]
Will be soon. apache-arrow 6.0.1 was just released which should fix all the bundler issues. I'll take a look at it tonight.

**Comment by ankoh** [comment]
Thanks for the workbook, the raw IPC stream works but serializing the externally constructed arrow table within our bundle seems to be break it. 
I'll take a closer look at it tomorrow.
https://observablehq.com/d/3a73e442912d9fde

**Comment by ankoh** [comment]
The root issue here was that all bundles targeted es2020. We switched to es2015.
This will work now on Observable:
https://observablehq.com/d/3a73e442912d9fde

**Comment by enjalot** [comment]
thank you!
