### ISSUE TITLE
jsdelivr fails on 0.1.13-dev8.0, missing duckdb-browser-async.worker.js

### ISSUE THREAD

**Issue by llimllib** [duckdb/duckdb-wasm#408]
I upgraded `@duckdb/duckdb-wasm` from `0.1.12-dev72.0` to `0.1.13-dev8.0`, and now trying to load the packages from jsdelivr fails:

```
GET https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@0.1.13-dev8.0/dist/duckdb-browser-async.worker.js
[HTTP/3 404 Not Found 166ms]
```

The equivalent file for `0.1.12-dev72.0` exists at https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@0.1.12-dev72.0/dist/duckdb-browser-async.worker.js.

I'm only running `const JSDELIVR_BUNDLES = duckdb.getJsDelivrBundles();`, not requesting this file myself

**Comment by llimllib** [comment]
I figured out how to work the bundle mechanism, I was pretty confused by the README, so I'll put it here:

- add a build-time task to copy files from duckdb-wasm's build folder to my own dist folder. I put them in `<root>/dist/duckdb` with this make task:

```make
# TODO: only copy this files if they're newer
duckdb_files: node_modules/@duckdb/duckdb-wasm/dist/*
	cp node_modules/@duckdb/duckdb-wasm/dist/*.{js,wasm,map} dist/duckdb/
```

- in my javascript code, tell duckdb how to use the bundles with the following:

```javascript
  const DUCKDB_BUNDLES = {
      asyncDefault: {
          mainModule: '/dist/duckdb/duckdb.wasm',
          mainWorker: '/dist/duckdb/duckdb-browser.worker.js',
      },
      asyncNext: {
          mainModule: '/dist/duckdb/duckdb-next.wasm',
          mainWorker: '/dist/duckdb/duckdb-browser-next.worker.js',
      },
      asyncNextCOI: {
          mainModule: '/dist/duckdb/duckdb-next-coi.wasm',
          mainWorker: '/dist/duckdb/duckdb-browser-next-coi.worker.js',
          pthreadWorker: '/dist/duckdb/duckdb-browser-next-coi.pthread.worker.js',
      },
  };
  const bundle = await duckdb.selectBundle(DUCKDB_BUNDLES);

```

**Comment by llimllib** [comment]
(I did this because I could no longer rely on jsdelivr, due to the bug above - I'd put off learning how it worked)

**Comment by ankoh** [comment]
Well spotting, thanks! This broke after changing the bundle names this afternoon.
I updated the URLs in ffdb492dde920c77b8f09137fac7ce17db3f41ec.
