### ISSUE TITLE
Don't materialize stream

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb-wasm#409]
Undo https://github.com/duckdb/duckdb-wasm/commit/35739b58347eafa95e0c429fda1396baafa8eb95 when https://issues.apache.org/jira/browse/ARROW-14780 is done and released.

**Comment by ankoh** [comment]
I think we can close this until DuckDB-Wasm gets async I/O. The overhead of this copy will rarely hurt if we cannot materialize directly into the wasm heap.
