### ISSUE TITLE
are parameterized queries supported?

### ISSUE THREAD

**Issue by enjalot** [duckdb/duckdb-wasm#441]
from what I can tell I can't do something like `conn.query("select * from test where field = $1", myVariable)`

is this not supported within DuckDB or just not exposed in the bindings?

**Comment by domoritz** [comment]
Yes, as prepared statements. See https://github.com/duckdb/duckdb-wasm/issues/117 and https://github.com/duckdb/duckdb-wasm/tree/master/packages/duckdb-wasm#prepared-statements.

I think we should automatically make a prepared statement in the [Observable client](https://observablehq.com/@cmudig/duckdb) when the user provides params (current ignored).

**Comment by ankoh** [comment]
Also:
https://github.com/duckdb/duckdb-wasm/blob/d3d150ddbaaaa435462ddc4a7b50ff1a4dd8b2f3/packages/duckdb-wasm/test/bindings.test.ts#L55-L61

**Comment by enjalot** [comment]
excellent, thanks for pointing me in the right direction!

I'm definitely motivated by supporting parameterized queries in the observable client.

**Comment by domoritz** [comment]
I just added support for parameterized queries to the Observable client at https://observablehq.com/@cmudig/duckdb.

**Comment by enjalot** [comment]
I'm struggling to find documentation on the prepared statements, and specifically how i could deal with array values. 

if i want to do something like `db.query("SELECT * FROM events WHERE device IN (?)", [["mobile", "desktop"]])` so that I don't have to prepare the right number of `?` in the query is that possible? I've been able to do this in PostgreSQL but not clear how standard that is across different SQL databases

**Comment by ankoh** [comment]
Ah interesting. Yes, we do not yet support arrays as parameter types, unfortunately.

**Comment by domoritz** [comment]
I filed https://github.com/duckdb/duckdb-wasm/issues/447. Luckily, the Observable client will just work when this is added.

**Comment by enjalot** [comment]
excellent, thanks for filing that one!
