### ISSUE TITLE
Interval type unsupported in query output

### ISSUE THREAD

**Issue by samansmink** [duckdb/duckdb-wasm#470]
Interval Type is not working as expected.

Query `SELECT INTERVAL '3' MONTH AS interval`
- on shell.duckdb.org: outputs an empty line.
- on DuckDB cli it returns: 

```
┌──────────┐
│ interval │
├──────────┤
│ 3 months │
└──────────┘
```

Reason for this appears to be that DuckDB sets the type for Interval to the Duration type ("tdm" type from [arrow c data interface docs](https://arrow.apache.org/docs/format/CDataInterface.html?highlight=tDm)). The Interval is converted to milliseconds in DuckDB. The duration type that is emitted by DuckDB, is not supported in Arrow JS. 

~The most likely option seems to be for DuckDB to emit an Interval type that JS does support. There seems to be some support for Intervals as the type is listed in the docs. If DuckDB emits interval [days, time] for the interval type DuckDB-WASM would be able to support intervals.~

(edit) Just discussed the possibility of emitting arrow interval types from DuckDB with mark, the problem is that the interval types of DuckDB and and arrow are not compatible. The best solution now seems to wait for the Duration type to be implemented in Arrow JS.

**Comment by ankoh** [comment]
CC @domoritz

**Comment by ankoh** [comment]
Can we use the time type?

**Comment by ankoh** [comment]
We have 2 other optional autocasts already. BigInt -> Double, Timestamp -> Date64. We could maybe just autocast Duration -> Time64? I can take a look at it next week.

**Comment by samansmink** [comment]
Yea thats the weird thing, the Time64 is working fine, so it seems trivial to also support the Duration type in Arrow JS, but maybe i'm missing something. Casting to Time64 seems like a good workaround!

**Comment by ankoh** [comment]
Awesome! Then I'd say we do exactly the same as in #393 and add the database option castDurationToTime64 which can probably just default to true in this case.

**Comment by samansmink** [comment]
That sounds like a great first PR for me 😁  I'll take a look!

**Comment by domoritz** [comment]
Note that in the next arrow version we want to embrace bigint more so that a conversion to float/two ints may not be necessary anymore. Just wanted to mention it so we can think about it for the api design.

**Comment by samansmink** [comment]
ah that very useful! thanks!
