### ISSUE TITLE
Extra cpp-folder in submodules/arrow-folder

### ISSUE THREAD

**Issue by kimmolinna** [duckdb/duckdb-wasm#473]
`make bootstrap` won't clone `arrow`-folder because of empty `cpp`-folder in `arrow`-folder.

**Comment by ankoh** [comment]
Can you please try to clone the repository to a new path? (Or alternatively delete `submodules/arrow` and run `git submodule update --init` again)
This is likely the result of a workaround that we use to make arrow play nicely with our ccache:
https://github.com/duckdb/duckdb-wasm/blob/60d0186dbcd7bb9e037f04403709fd812455f4a6/lib/cmake/arrow.cmake#L56

**Comment by kimmolinna** [comment]
This was mainly FYI. I was able to clone everything after this change. I had some issue with older ccache but when I updated to the newest version everything worked nicely.

**Comment by ankoh** [comment]
Thanks for reporting this.
I think this targets the general simplification of the dev setup.
Right now, building duckdb-wasm is still fairly complicated.
I'll close this for now.
