### ISSUE TITLE
cast decimal to double option

### ISSUE THREAD

**Issue by samansmink** [duckdb/duckdb-wasm#477]
Just found out that Arrow JS has a open issue where negative decimal types do not work properly ([link](https://issues.apache.org/jira/browse/ARROW-6575))

Maybe its good idea to add a fourth cast option similarly to PR #476 called `castDecimalToDouble`? I can do another PR for it?

**Comment by ankoh** [comment]
Sure, sounds good! We can just add a deprecation warning later when they are resolved. 👍🏻

**Comment by bluehat974** [comment]
Weird negative number will be solved in apache-arrow 13
https://github.com/apache/arrow/pull/35067
