### ISSUE TITLE
Add bundle for WASM exceptions without SIMD. 

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb-wasm#536]
Safari 15.2 supports exceptions and it would be nice if we could benefit from them in duckdb.

**Comment by domoritz** [comment]
Safari 15.2 ships with iOS and iPadOS 15.2 and macOS 12.1. https://developer.apple.com/documentation/safari-release-notes/safari-15_2-release-notes

**Comment by ankoh** [comment]
Lets flip this with b17d6a7d541eec25fedfd2207ce3146530134214 . We can add a dedicated SIMD bundle later but the effect is significantly smaller than wasm eh.
