### ISSUE TITLE
What do COI and EH mean?

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb-wasm#629]
Maybe a dumb question, but I wasn't able to find answers on my own by reading the code. What do "COI" and "EH" mean? (I presume "MVP" means "minimum viable product," but maybe that's wrong?)

**Comment by Alex-Monahan** [comment]
I belive coi is [cross origin isolation](https://web.dev/why-coop-coep/), and EH is [exception handling](https://github.com/WebAssembly/exception-handling/blob/main/proposals/exception-handling/Exceptions.md)

Does that help?

**Comment by zenazn** [comment]
Yes! Thank you

**Comment by manzt** [comment]
what is MVP?

**Comment by carlopi** [comment]
MVP comes from the WebAssembly jargon, it stands for Minimum Viable Product that is the working-name (that then has been kept around) for the first stable version of the WebAssembly standard.

See for example here: https://github.com/WebAssembly/design/blob/main/MVP.md

**Comment by manzt** [comment]
thank you!!
