### ISSUE TITLE
Online shell font looks weird

### ISSUE THREAD

**Issue by davidgasquez** [duckdb/duckdb-wasm#676]
#### What happens?
The rendering of the https://shell.duckdb.org/ shell font looks odd. 

![1646991083](https://user-images.githubusercontent.com/1682202/157840873-d8a87348-9cc8-4c54-a941-4e80ea5ac947.png)

#### To Reproduce
Open https://shell.duckdb.org/.

#### Environment (please complete the following information):
 - OS: Arch Linux
 - Browser Version: Brave Browser 99.1.36.112

**Comment by domoritz** [comment]
Sounds like this can be closed since it's out of the scope of duckdb-wasm.
