### ISSUE TITLE
Range requests of remote files not supported for S3 presigned URLs

### ISSUE THREAD

**Issue by mjbcopland** [duckdb/duckdb-wasm#699]
https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html

> When you create a presigned URL for your object, you must provide your security credentials and then specify a bucket name, an object key, **an HTTP method (GET to download the object)**, and an expiration date and time. 

Emphasis mine. Presigned URLs are only valid for a single method, i.e. if we create a GET URL to download a remote file, we cannot use HEAD on that URL.

```js
await connection.query("select * from '<presigned_get_url>'");
```

Globbing this URL fires of a HEAD request which returns 403 and the overall query fails with `Uncaught (in promise) Error: WebAssembly.Exception: wasm exception`.

This can be avoided by registering the URL directly.

```js
await db.registerFileURL("<filename>", "<presigned_get_url>");
await connection.query("select * from '<filename>'");
```

But this still executes a HEAD request during `openFile()` in an attempt to read Content-Length, and results in warning `falling back to full HTTP read` despite the fact that S3 supports range requests (but not HEAD on a URL that was signed for GET).

I've managed to get around this issue by creating my own runtime which doesn't use a HEAD request but rather requests only a single byte, then creating my own worker which uses this runtime.

```js
    const xhr = new XMLHttpRequest();

    xhr.open("GET", file.dataUrl, false);
    xhr.setRequestHeader("Range", "bytes=0-0");
    xhr.send(null);

    const contentRange = xhr.getResponseHeader("Content-Range");
    const contentLength = contentRange?.match(/bytes 0-0\/(\d+)/)?.at(1);
```

It works but took a lot of reverse engineering and I've currently made assumptions about S3. It feels a little hacky and almost like fighting against the original library. However, a comment would suggest that this is the original intent. Or perhaps, it was at one point? 

> [`// Send a dummy range request querying the first byte of the file`](https://github.com/duckdb/duckdb-wasm/blob/bc84cbf/packages/duckdb-wasm/src/bindings/runtime_browser.ts#L151)

Arguably a HEAD request is the proper way to fetch content length, but it clearly doesn't work for presigned URLs. Another approach could be to specify two data URLs, one for HEAD and one for GET, but I don't know how easy that would be to integrate.

Are there any other workarounds or fixes for this issue? How else might we be able to support this?

**Comment by ankoh** [comment]
Thanks for reporting this.
Yes we deliberately switched to HEAD requests a while ago to defuse the situation where the remote would just ignore the range header and would send us everything instead.
By default, DuckDB-Wasm will only download the entire file as fallback for unsupported range headers if a configuration option set.

I didn't consider presigned URLs though.
Maybe we can switch back to `GET bytes=0-1` and abort the download in the progress handler instead.

**Comment by mjbcopland** [comment]
I think HEAD requests still make sense for the majority of use cases. I just found it hard to override this behaviour for niche cases, e.g. presigned urls.

fwiw I ended up importing `BROWSER_RUNTIME` and `createDuckDB` from `@duckdb/duckdb-wasm/dist/duckdb-browser-blocking` and using it to create my own worker with a custom `openFile`, but it took a lot of reverse engineering of the original source code and I still don't fully understand how it works.

I don't think that the published package necessarily has to go back to using `GET bytes=0-0` but it would be nice if there was a better approach to injecting custom logic.

**Comment by carlopi** [comment]
Hi @mjbcopland, I just re-discovered this thread while working on something related and considering a partial refactor of the handling of files.

I took the liberty of using the logic you suggested (https://github.com/carlopi/duckdb-wasm/commit/e1fe41624065967d165fb63c0f8c7c741cd27cdf), and I am considering whether the whole HTTP-backend should be able to handle fallible HEAD requests (falling back purely to GETs).

The problem with generalizing your solution is that there are servers (like github.rawusercontent.com) that do not serve Content-Range in a CORS-readable way.

Thanks for the report in any case.

**Comment by carlopi** [comment]
I am considering this fixed for now. @mjbcopland, could you potentially give it a try, happy to patch if something is still non functional.

**Comment by dude0001** [comment]
@mjbcopland can you share a bit more about what you did to work around?

On @duckdb/duckdb-wasm@1.27.0 I see a 403 from an initial HTTP HEAD to S3 pre-signed URL, which would be expected since the pre-signed URL is only for GET.

Then I see a GET that does not send a `Range` header, and it reads the entire file in a 200 OK response.
