### ISSUE TITLE
Enabling extensions in the wasm build

### ISSUE THREAD

**Issue by david542542** [duckdb/duckdb-wasm#839]
It would be nice to be able to easily make the wasm build by including one or more extensions, such as the [JSON](https://duckdb.org/docs/extensions/json) one. And I'm sure as the project involves there will be many more practical extensions that someone might want to use, so I'll break this down into two items:

1. It would be great to have instructions for a developer to be able to build wasm with various extensions.
2. It would be great to show an example with the most commonly used JSON extension as an additional target.

Of course adding additional extensions will add size to the bundle, and I think the size with/without the JSON extension will show approximately how much additional size each extension will add (though it's of course highly dependent on what the extension is).

**Comment by ankoh** [comment]
Shipping extensions by default in all of our bundles bloats the module sizes for everyone, we already did this for Parquet and FTS but we have to be a bit careful here.
Especially since duckdb-wasm already has a dedicated efficient json import.

**Comment by david542542** [comment]
@ankoh cool, in terms of adding in an extension loading mechanism, how much work do you think that might involve? Seems like being in experimental territory should probably be fine, since the whole extension/plugin framework seems pretty new and all.

**Comment by srossross** [comment]
> It would be great to have instructions for a developer to be able to build wasm with various extensions

I'm building an extension starting from https://github.com/duckdb/extension-template/. I am curious how to compile it to wasm - google lead me here, but I can not find other documentation, can anyone point me in the right direction?
