### ISSUE TITLE
Increase memory limit to 4GB?

### ISSUE THREAD

**Issue by mewim** [duckdb/duckdb-wasm#840]
It seems that duckdb-wasm has a memory limit of 1.7GB, which might be due to the 2GB memory limit of WebAssembly previously. 

```
duckdb> PRAGMA database_size;
┌───────────────┬────────────┬──────────────┬─────────────┬─────────────┬──────────┬──────────────┬──────────────┐
│ database_size ┆ block_size ┆ total_blocks ┆ used_blocks ┆ free_blocks ┆ wal_size ┆ memory_usage ┆ memory_limit │
╞═══════════════╪════════════╪══════════════╪═════════════╪═════════════╪══════════╪══════════════╪══════════════╡
│               ┆            ┆              ┆             ┆             ┆          ┆ 0 bytes      ┆ 1.7GB        │
└───────────────┴────────────┴──────────────┴─────────────┴─────────────┴──────────┴──────────────┴──────────────┘
Elapsed: 2 ms
```

Now, it seems that the major browsers can support a 4GB memory limit, and it requires only setting up a flag for emcc to according to [Up to 4GB of memory in WebAssembly](https://v8.dev/blog/4gb-wasm-memory#:~:text=Thanks%20to%20recent%20work%20in,512MB%20or%201GB%20of%20memory!). Could the support for 4GB memory be enabled for duckdb-wasm or does it require extra work?

**Comment by ankoh** [comment]
Good catch, yes we should support 4GB heap memory in Chrome.
But if this is exclusive to Chrome, we have to ship dedicated wasm modules and I'm undecided if we should just double our module count here.
Today, we are already shipping a module for the minimum wasm MVP feature profile, a module with exception handling enabled, and an experimental one for shared array buffers.

**Comment by mewim** [comment]
Hi @ankoh,

Thanks for your reply. It seems according to [this ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1660420),
> the maximum_memory is just a hint and not an enforcement hence it should not affect invocation to `memory.grow()` as long as the the memory is not growing beyond the browser enforced limits. 
So maybe it is fine to just distribute one binary with 4GB memory limit without breaking the compatibility of other browsers?

**Comment by ankoh** [comment]
<img width="1377" alt="Screenshot 2022-07-18 at 15 54 24" src="https://user-images.githubusercontent.com/3986510/179527059-7c9fafbc-1570-44d5-917f-875788440b91.png">

Added in 78564bbb220302cc532de91ea6182f8f89322798
