### ISSUE TITLE
Implement cancelable query API

### ISSUE THREAD

**Issue by david542542** [duckdb/duckdb-wasm#871]
Should be able to implement a way to cancel a query from the API even though DuckDB doesn't currently support concurrency. Also, can't just destroy a connection if that connection has in-memory tables (that would be lost of closing it).

**Comment by ankoh** [comment]
The connection now provides the method `cancelSent` to cancel a query that was executed asynchronously using `send`.
https://github.com/duckdb/duckdb-wasm/blob/c43a2ccd21669efc3932418356a70ce00a757821/packages/duckdb-wasm/src/parallel/async_connection.ts#L74

As potentially breaking change, the method `send` on the synchronous bindings is not asynchronous as well.
https://github.com/duckdb/duckdb-wasm/blob/c43a2ccd21669efc3932418356a70ce00a757821/packages/duckdb-wasm/src/bindings/connection.ts#L59

**Comment by chenxi8611** [comment]
These APIs are great.
I would like to test these APIs, can you let me know how I can test these APIs properly?

**Comment by ankoh** [comment]
The connection just calls those internally:
https://github.com/duckdb/duckdb-wasm/blob/86032f2d703bb92fff2d91fe110f80ab92cdc487/packages/duckdb-wasm/src/bindings/connection.ts#L60
