### ISSUE TITLE
Sum of integer fields results in a 4 element Uint32Array instead of a number

### ISSUE THREAD

**Issue by DingoEatingFuzz** [duckdb/duckdb-wasm#873]
Maybe this is a user/documentation error, but I was surprised by this result.

**What happened**

Given this table:

| id | foo (integer) |
| --- | --------- |
| 1 | 10 |
| 2 | 20 |
| 3 | 50 |

```sql
SELECT sum(foo) FROM table
```

results in a record with the shape

```
{
  "sum(foo)": Uint32Array<80,0,0,0>
}
```

**What was expected**

A record with the shape

```
{
  "sum(foo)": 80
}
```

Incidentally, if the data type for the column is `double`, the result _is_ a number, and it will also overflow 😳 

I kind of assume this is an intentional overflow protection, but I wanted to be safe and raise an issue instead of assuming things. Thanks!

**Comment by DingoEatingFuzz** [comment]
Never mind! I fell further down this rabbithole and learned some things I'll document here in case someone ends up on this issue in the future.

1. The result is not a 4 element `Uint32Array`. If you check out the constructor of the object, it's actually a [`DecimalBigInt`](https://github.com/apache/arrow/blob/master/js/src/util/bn.ts) from the Arrow library.
2. These objects can be cast to values using `valueOf` (which JS will do automatically when coercing)
3. The resulting number isn't likely going to be what you expect...for reasons I'm still not sure...but you can get the number you would expect with the following:
   ```js
   BigInt.asIntN(32, record.foo) // 80n
   ```

Just note that when you do a [BigInt conversion](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt/asIntN), you get a `BigInt` back. So if you want to do follow up math you either have to do your math with more `BigInts` or convert to a number (potentially unsafe!! This can cause an overflow which is why BigInts exist in the first place).

```js
// Using BigInts
BigInt.asIntN(32, record.foo) / 2n; // 40n

// Using converstion
Number(BigInt.asIntN(32, record.foo) / 2; // 40
```

**Comment by domoritz** [comment]
I'm a bit confused. Arrow should support bigints and return them from calls on a `Table`. Can you specify what api you called to get your output?

**Comment by DingoEatingFuzz** [comment]
Yeah, most of what I have has been more or less copy/pasted from yours (and others) Observable template: https://observablehq.com/@cmudig/duckdb

So the call stack more or less looks like:

1. Receive Arrow DecimalBigInt from:
2. A record in the `rows` object which comes from
3. `result.toArray().map(Object.fromEntries)` where `result` comes from
4. `db.query` which calls
5. `statement.query` which calls
6. ??? DuckDB stuff

This is all from an open source thing I'm playing with so I can provide code links to if surrounding context is useful:

1. [Converting a field on the record to a `BigInt`](https://github.com/DingoEatingFuzz/climate-dashboard/blob/main/vega-lite/app.js#L257)
2. [Indirect query through a db layer](https://github.com/DingoEatingFuzz/climate-dashboard/blob/main/vega-lite/app.js#L235)
3. [The query itself](https://github.com/DingoEatingFuzz/climate-dashboard/blob/main/db/index.js#L120-L143)  (which is admittedly also doing weird client-side join stuff, but I ruled that out)
4. [The familier `query` implementation](https://github.com/DingoEatingFuzz/climate-dashboard/blob/main/db/index.js#L60-L78)
5. [The familiar `makeDB` implementation](https://github.com/DingoEatingFuzz/climate-dashboard/blob/main/db/index.js#L3-L12)

**Comment by domoritz** [comment]
I'd avoid mapping Object.fromEntries since it makes a copy and kills performance. Can you directly work with arrow?

**Comment by DingoEatingFuzz** [comment]
Potentially! The performance issue is good to know about. At this moment in my project I'm not too concerned about performance--honestly the whole DuckDB component was just a fun aside for this climate dashboard, which itself is kind of a fun aside from research into various data viz libraries, which is also a fun aside from building out a data viz component library in Ember. 

But library interop and data transformation is a big piece of data viz, so it makes sense to work some of that into these reference implementations.

Do you think the `Object.fromEntries` is what's causing the `BigInt` type coercion then?

**Comment by domoritz** [comment]
> Do you think the Object.fromEntries is what's causing the BigInt type coercion then?

Potentially. But ideally we should be using bigints all the way. Could you try to reproduce the issue on Observable with data being directly generated in a query so I can try to dig into what's happening?
