### ISSUE TITLE
Read-only access

### ISSUE THREAD

**Issue by ixxie** [duckdb/duckdb-wasm#908]
It would be great to support read-only connections in duckdb-wasm! 

FWIW in our usecase, we want the backend to drive mutating database operations through endpoints, and while allowing the frontend to run non-mutating analytical queries freely.

**Comment by carlopi** [comment]
Would by any chance this PR by @whscullin work in your use case: https://github.com/duckdb/duckdb-wasm/pull/1260.

It allows read-only databases, that should be more or less what you are looking for.
