### ISSUE TITLE
Simple range select causes infinite loop

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb-wasm#949]
## To reproduce
```sql
select ['a'] as i from range(10) tbl(i);
```

## Environment details

Client: shell.duckdb.org
Version: 0.4.0 (@duckdb/duckdb-wasm@1.16.1-dev51.0)

## Reproducable outside of WASM?

I have tried this same query on DuckDB CLI (master:latest), it completes just fine there

**Comment by carlopi** [comment]
Current live version, @duckdb/duckdb-wasm@1.20.1-dev33.0, seems to work as expected (Chrome / Safari / Firefox), could you possibly give it another try?

**Comment by Tishj** [comment]
```
duckdb> select ['a'] as i from range(10) tbl(i);
┌─────┐
│ i   │
╞═════╡
│ [a] │
│ [a] │
│ [a] │
│ [a] │
│ [a] │
│ [a] │
│ [a] │
│ [a] │
│ [a] │
│ [a] │
└─────┘
```
👍
