### ISSUE TITLE
date_part is not working with DuckDBClient in ObservableHQ [RangeError: Maximum call stack size exceeded.]

### ISSUE THREAD

**Issue by kimmolinna** [duckdb/duckdb-wasm#983]
@domoritz The following example from web page is not working in ObservableHQ with Safari or Chrome/IOS:
`SELECT date_part('minute', TIMESTAMP '1992-09-20 20:38:40')`  and it’s working in shell.duckdb.org

**Comment by kimmolinna** [comment]
This is working when you reload the page. I don’t understand why…

**Comment by kimmolinna** [comment]
Or actually you just have to reload the client.

**Comment by domoritz** [comment]
Can you send a link to a notebook and what browser you are using?

**Comment by kimmolinna** [comment]
https://observablehq.com/d/7699b0c727da6fb5
There isn't any problem with my computer but on IOS/Safari and Chrome I have to re-run the client all the time to get the changes work. Then It work without any problem.

**Comment by domoritz** [comment]
The notebook works fine for me in Safari now. Is this still an issue?

**Comment by kimmolinna** [comment]
I will still get the following error message: `RangeError: Maximum call stack size exceeded.` Do I have somehow wrong settings on my IOS/Safari?

**Comment by domoritz** [comment]
Not sure. Can you post a minimal example that shows the issue? I don't have problems with date part.

**Comment by kimmolinna** [comment]
When you open the Notebook it works nicely but if you re-run the cell you will get `RangeError: Maximum call stack size exceeded.`
https://observablehq.com/@kimmolinna/date_part-test

**Comment by domoritz** [comment]
I can't reproduce this issue (tried rerunning the cell a few times) in the latest Safari 16. Which version are you using?

**Comment by kimmolinna** [comment]
The iPadOS version is 15.7 which is the latest my employer has approved so I assuma my Safari version on iPad is then 15.

**Comment by domoritz** [comment]
I'd say this may be a fixed browser issue then and I don't think it makes sense for us to investigate.

**Comment by domoritz** [comment]
Closing. Let's reopen if we can repro in latest safari.
